# Generated by Django 3.2.4 on 2021-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('COL', 'Colombia'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('CHL', 'Chile'), ('NLD', 'Netherlands')], default='', max_length=3),
        ),
    ]
